import React from "react";

class Challenge2 extends React.Component {
  render() {
    return (
      <div>
        <h1>Challenge 2</h1>
        <h2>
          Each new term in the Fibonacci sequence is generated by adding the
          previous two terms. By starting with 1 and 2, the first 10 terms will
          be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        </h2>
        <h2>
          By considering the terms in the Fibonacci sequence whose values do not
          exceed your chosen number, find the sum of the even-valued terms.
        </h2>
        <form onSubmit={this.props.challenge2}>
          <input
            className="inputBox"
            placeholder="Your Number"
            value={this.props.yourNumber}
            onChange={this.props.handleChange}
          />
        </form>
        <div className="resultBox">
          <h3>{this.props.result}</h3>
        </div>
      </div>
    );
  }
}

export default Challenge2;
